# Server
server:
  port: "8090"

# JPA
spring:
  datasource:
    url: jdbc:h2:mem:hdf
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect